/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.tu_bs.cs.isf.e4cf.gradle_build;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
