<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CrossTreeConstraints" nsURI="www.example.com/CrossTreeConstraints"
    nsPrefix="CTC">
  <eClassifiers xsi:type="ecore:EClass" name="Formula" eSuperTypes="#//AbstractConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//Operator"
        defaultValueLiteral="NONE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formula" upperBound="-1"
        eType="#//AbstractConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Operator">
    <eLiterals name="AND"/>
    <eLiterals name="OR" value="1"/>
    <eLiterals name="IMPLIES" value="2"/>
    <eLiterals name="EQUALS" value="4" literal="EQUALS"/>
    <eLiterals name="NONE" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//AbstractConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractConstraint" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNegated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;&quot;"/>
  </eClassifiers>
</ecore:EPackage>
