package de.tu_bs.cs.isf.e4cf.compare.data_structures.io.reader;

/**
 * This file extends the nodes types and attributes for the generic data structure generated by @see Visitor 
 * 
 * @author Serkan Acar
 * @author Pascal Blum
 * @author Paulo Haas
 * @author Hassan Smaoui
 */
public enum JavaNodeTypes {
	Argument,
	Assignment,
	BlockComment,
	Body,
	Bound,
	Break,
	Cast,
	Class,
	Continue, 
	Else,
	Import, 
	Interface,
	JavadocComment,
	LineComment,
	Synchronized,
	Then,
}
