package de.tu_bs.cs.isf.e4cf.compare.data_structures.io.reader;

/**
 * This file extends the nodes types and attributes for the generic data structure generated by @see Visitor 
 * 
 * @author Serkan Acar
 * @author Pascal Blum
 * @author Paulo Haas
 * @author Hassan Smaoui
 */
public enum JavaNodeTypes {
	Annotation,
	Argument,
	Assignment,
	Asterisks,
	Body,
	Bound,
	Break,
	Cast,
	Check,
	Children,
	Class,
	Comparison,
	Condition,
	Continue, 
	Default,
	Else,
	Expression,
	Field,
	Identifier,
	Import, 
	Initilization,
	Interface,
	isInterface,
	Iterator,
	Key,
	Message,
	Modifier,
	Name,
	Package,
	ReturnType,
	Scope,
	Selector,
	Statement,
	Static, 
	Superclass,
	Synchronized,
	Target,
	Then,
	Throws,
	Type,
	Update,
	Value,
}
