<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="FeatureConfiguration" nsURI="www.feature.configuration.de" nsPrefix="fc">
  <eClassifiers xsi:type="ecore:EClass" name="FeatureConfiguration">
    <eOperations name="toString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureSelection" upperBound="-1"
        eType="#//FeatureToBooleanMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureDiagram" eType="ecore:EClass ../../de.tu_bs.cs.isf.e4cf.featuremodel.model/model/feature-metamodel.ecore#//FeatureDiagramm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureToBooleanMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="ecore:EClass ../../de.tu_bs.cs.isf.e4cf.featuremodel.model/model/feature-metamodel.ecore#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
  </eClassifiers>
</ecore:EPackage>
