<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SolutionModel" nsURI="www.tu-bs.de/isf/solution_model" nsPrefix="SM">
  <eClassifiers xsi:type="ecore:EClass" name="AbstractSolutionElement" abstract="true"
      eSuperTypes="#//IUpdate #//IFamilyModelAdapter">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eTypeParameters>
    <eOperations name="resetElement" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Similarity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elements" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractContainer" abstract="true" eSuperTypes="#//AbstractSolutionElement">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractoption" upperBound="-1"
        eType="#//AbstractOption" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractresult" upperBound="-1"
        eType="#//AbstractResult" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractOption" abstract="true" eSuperTypes="#//AbstractSolutionElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractcontainer" upperBound="-1"
        eType="#//AbstractContainer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractResult" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass metrc.ecore#//AbstractAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IUpdate" abstract="true" interface="true">
    <eOperations name="updateSimilarity" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IFamilyModelAdapter" abstract="true"
      interface="true">
    <eOperations name="getLeftLabel" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getRightLabel" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
